### ISSUE TITLE
Should be able to localize individual components in paths/url section

### ISSUE THREAD

**Issue by tdreyno** [middleman/middleman-i18n#4]
```
es:
  paths:
    hello: "hola"
    mister: "senor"
```

/hello/mister.html -> /hola/senor.html
